module.exports = {
  collectCoverage: true,
  collectCoverageFrom: ['src/components/**/*.js?(x)', '!src/**/*.story.js?(x)'],
  coveragePathIgnorePatterns: ['/node_modules/', '/lib/', '/coverage/'],
  coverageReporters: ['html', 'text-summary'],
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 80,
      functions: 80,
      lines: 80,
    },
    './src/components/**/!(ColumnHeaderRow|ColumnHeaderSelect|FilterHeaderRow|TableToolbar|RowActionsCell|RowActionsError|StatefulWizardInline|WizardInline|StatefulTable|StatefulTableDetailWizard|CatalogContent|FileDrop|HeaderMenu|Dashboard|CardRenderer|Attribute|UnitRenderer|ImageHotspots|ImageControls|TimeSeriesCard|ListCard|StatefulPageWizard|PageHero|PageTitle|EditPage|AsyncTable|ImageCard|WizardHeader).jsx': {
      statements: 80,
      branches: 80,
      functions: 80,
      lines: 80,
    },
    // The overrides below are to be fixed/deleted via https://github.com/IBM/carbon-addons-iot-react/issues/707
    './src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.jsx': { branches: 70 },
    './src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx': { branches: 70 },
    './src/components/Table/TableToolbar/TableToolbar.jsx': { functions: 66 },
    './src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx': {
      statements: 79,
      branches: 70,
      lines: 78,
      functions: 75,
    },
    './src/components/Table/TableBody/RowActionsCell/RowActionsError.jsx': { functions: 66 },
    './src/components/WizardInline/StatefulWizardInline.jsx': { branches: 53 },
    './src/components/Table/StatefulTable.jsx': { branches: 66 },
    './src/components/TileCatalog/CatalogContent.jsx': { branches: 50 },
    './src/components/FileDrop/FileDrop.jsx': { branches: 53, functions: 75 },
    './src/components/Header/HeaderMenu.jsx': { branches: 71 },
    './src/components/Dashboard/Dashboard.jsx': { statements: 79, branches: 50, lines: 78 },
    './src/components/Dashboard/CardRenderer.jsx': {
      statements: 51,
      branches: 38,
      lines: 51,
      functions: 66,
    },
    './src/components/ValueCard/Attribute.jsx': { branches: 65, functions: 66 },
    './src/components/ValueCard/UnitRenderer.jsx': {
      statements: 70,
      branches: 8,
      lines: 70,
      functions: 25,
    },
    './src/components/ImageCard/ImageHotspots.jsx': {
      statements: 78,
      branches: 61,
      lines: 78,
      functions: 50,
    },
    './src/components/ImageCard/ImageControls.jsx': { branches: 66 },
    './src/components/TimeSeriesCard/TimeSeriesCard.jsx': {
      statements: 70,
      branches: 50,
      lines: 69,
      functions: 77,
    },
    './src/components/ListCard/ListCard.jsx': { branches: 66 },
    './src/components/PageWizard/StatefulPageWizard.jsx': {
      statements: 12,
      branches: 0,
      lines: 13,
      functions: 0,
    },
    './src/components/Page/EditPage.jsx': {
      statements: 64,
      branches: 50,
      lines: 64,
      functions: 50,
    },
    './src/components/Table/AsyncTable/AsyncTable.jsx': {
      statements: 56,
      branches: 50,
      lines: 60,
      functions: 13,
    },
    './src/components/Table/TableHead/ColumnHeaderSelect/ColumnHeaderSelect.jsx': { branches: 75 },
    './src/components/WizardInline/WizardInline.jsx': { branches: 77 },
    './src/components/WizardInline/WizardHeader/WizardHeader.jsx': { branches: 75 },
    './src/components/Page/PageHero.jsx': { branches: 77 },
    './src/components/Page/PageTitle.jsx': { branches: 75 },
    './src/components/ImageCard/ImageCard.jsx': { branches: 76 },
    './src/components/Table/TableDetailWizard/StatefulTableDetailWizard.jsx': { branches: 76 },
  },
  globals: {
    __DEV__: false,
  },
  setupFiles: ['<rootDir>/config/jest/setup.js'],
  setupFilesAfterEnv: ['<rootDir>/config/jest/setupTest.js'],
  testMatch: [
    '<rootDir>/**/__tests__/**/*.js?(x)',
    '<rootDir>/**/?(*.)(spec|test).js?(x)',
    '<rootDir>/**/?(*.)test.a11y.js?(x)',
  ],
  testURL: 'http://localhost',
  transform: {
    '^.+\\.jsx?$': 'babel-jest',
    '^.+\\.s?css$': '<rootDir>/config/jest/cssTransform.js',
    '^(?!.*\\.(js|jsx|css|json)$)': '<rootDir>/config/jest/fileTransform.js',
  },
  testPathIgnorePatterns: ['/config/', '/lib/'],
  transformIgnorePatterns: ['/node_modules/(?!(@carbon/charts)).+(.jsx?)'],
  watchPathIgnorePatterns: ['/coverage/', '/results/', '/.git/'],
  moduleFileExtensions: ['js', 'json', 'jsx'],
  snapshotSerializers: ['enzyme-to-json/serializer'],
};
