export const SUITE_HEADER_ROUTE_TYPES = {
  ADMIN: 'ADMIN',
  NAVIGATOR: 'NAVIGATOR',
  REFERRER: 'REFERRER',
  APPLICATION: 'APPLICATION',
  PROFILE: 'PROFILE',
  ABOUT: 'ABOUT',
  LOGOUT: 'LOGOUT',
  DOCUMENTATION: 'DOCUMENTATION',
  SURVEY: 'SURVEY',
};
