export const keyboardKeys = {
  BACKSPACE: 'Backspace',
  CONTROL: 'Control',
  DELETE: 'Delete',
  DOWN: 'ArrowDown',
  END: 'End',
  ENTER: 'Enter',
  ESCAPE: 'Escape',
  HOME: 'Home',
  LEFT: 'ArrowLeft',
  PAGEDOWN: 'Page Down',
  PAGEUP: 'Page Up',
  RIGHT: 'ArrowRight',
  SPACE: ' ',
  TAB: 'Tab',
  UP: 'ArrowUp',
};
